remote_theme: pages-themes/cayman@v0.2.0
title: SciCodes 2025
description: An Alfred P. Sloan Foundation funded symposium and 2nd collaborative workshop for editors and maintainers of scientific software registries and repositories
repository: scicodes/workshop-2025
show_downloads: "false"
plugins:
  - jekyll-remote-theme
